services:
  web:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__DOMAIN=umbrel.local
      - GITEA__server__ROOT_URL=http://umbrel.local:3000
      - GITEA__server__HTTP_PORT=3000
    ports:
      - '3000:3000'
      - '2222:22'
    volumes:
      - /home/umbrel/umbrel/app-data/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
